//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTicTacToeEkzamen.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameHelper", Namespace="http://schemas.datacontract.org/2004/07/TicTacToeWCFService")]
    [System.SerializableAttribute()]
    public partial class GameHelper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFTicTacToeEkzamen.ServiceReference1.CellType[] FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGameEndedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PlayersTurnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFTicTacToeEkzamen.ServiceReference1.CellType[] Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGameEnded {
            get {
                return this.IsGameEndedField;
            }
            set {
                if ((this.IsGameEndedField.Equals(value) != true)) {
                    this.IsGameEndedField = value;
                    this.RaisePropertyChanged("IsGameEnded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PlayersTurn {
            get {
                return this.PlayersTurnField;
            }
            set {
                if ((this.PlayersTurnField.Equals(value) != true)) {
                    this.PlayersTurnField = value;
                    this.RaisePropertyChanged("PlayersTurn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CellType", Namespace="http://schemas.datacontract.org/2004/07/TicTacToeWCFService")]
    public enum CellType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMPTY = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRESTIK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOLIK = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITicTakService", CallbackContract=typeof(WPFTicTacToeEkzamen.ServiceReference1.ITicTakServiceCallback))]
    public interface ITicTakService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicTakService/GetGameHelper", ReplyAction="http://tempuri.org/ITicTakService/GetGameHelperResponse")]
        WPFTicTacToeEkzamen.ServiceReference1.GameHelper GetGameHelper();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicTakService/GetGameHelper", ReplyAction="http://tempuri.org/ITicTakService/GetGameHelperResponse")]
        System.Threading.Tasks.Task<WPFTicTacToeEkzamen.ServiceReference1.GameHelper> GetGameHelperAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicTakService/setGameHelper", ReplyAction="http://tempuri.org/ITicTakService/setGameHelperResponse")]
        void setGameHelper(WPFTicTacToeEkzamen.ServiceReference1.GameHelper Game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicTakService/setGameHelper", ReplyAction="http://tempuri.org/ITicTakService/setGameHelperResponse")]
        System.Threading.Tasks.Task setGameHelperAsync(WPFTicTacToeEkzamen.ServiceReference1.GameHelper Game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicTakService/Connect", ReplyAction="http://tempuri.org/ITicTakService/ConnectResponse")]
        bool Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicTakService/Connect", ReplyAction="http://tempuri.org/ITicTakService/ConnectResponse")]
        System.Threading.Tasks.Task<bool> ConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicTakService/MakeTurn", ReplyAction="http://tempuri.org/ITicTakService/MakeTurnResponse")]
        void MakeTurn(int cellNumb, WPFTicTacToeEkzamen.ServiceReference1.CellType symb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicTakService/MakeTurn", ReplyAction="http://tempuri.org/ITicTakService/MakeTurnResponse")]
        System.Threading.Tasks.Task MakeTurnAsync(int cellNumb, WPFTicTacToeEkzamen.ServiceReference1.CellType symb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITicTakServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicTakService/GetGame", ReplyAction="http://tempuri.org/ITicTakService/GetGameResponse")]
        void GetGame(WPFTicTacToeEkzamen.ServiceReference1.CellType game);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITicTakServiceChannel : WPFTicTacToeEkzamen.ServiceReference1.ITicTakService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicTakServiceClient : System.ServiceModel.DuplexClientBase<WPFTicTacToeEkzamen.ServiceReference1.ITicTakService>, WPFTicTacToeEkzamen.ServiceReference1.ITicTakService {
        
        public TicTakServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TicTakServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TicTakServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TicTakServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TicTakServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public WPFTicTacToeEkzamen.ServiceReference1.GameHelper GetGameHelper() {
            return base.Channel.GetGameHelper();
        }
        
        public System.Threading.Tasks.Task<WPFTicTacToeEkzamen.ServiceReference1.GameHelper> GetGameHelperAsync() {
            return base.Channel.GetGameHelperAsync();
        }
        
        public void setGameHelper(WPFTicTacToeEkzamen.ServiceReference1.GameHelper Game) {
            base.Channel.setGameHelper(Game);
        }
        
        public System.Threading.Tasks.Task setGameHelperAsync(WPFTicTacToeEkzamen.ServiceReference1.GameHelper Game) {
            return base.Channel.setGameHelperAsync(Game);
        }
        
        public bool Connect() {
            return base.Channel.Connect();
        }
        
        public System.Threading.Tasks.Task<bool> ConnectAsync() {
            return base.Channel.ConnectAsync();
        }
        
        public void MakeTurn(int cellNumb, WPFTicTacToeEkzamen.ServiceReference1.CellType symb) {
            base.Channel.MakeTurn(cellNumb, symb);
        }
        
        public System.Threading.Tasks.Task MakeTurnAsync(int cellNumb, WPFTicTacToeEkzamen.ServiceReference1.CellType symb) {
            return base.Channel.MakeTurnAsync(cellNumb, symb);
        }
    }
}
